---
# redmine.example.com
version: '2'
services:
  mail:
    image: elsdoerfer/exim-sender

  db:
    image: mysql:latest
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=admin
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    volumes:
       - ./db_data:/var/lib/mysql
       - ./db/init:/docker-entrypoint-initdb.d

  app:
    build: ./app
    links:
      - db
      - mail
    volumes:
      - ./redmine_files:/home/app/redmine/files/:rw                                                                                                                                                                 
      - ./redmine_ssh:/home/app/.ssh                  
      - ./themes-enabled:/home/app/redmine/public/themes/                                                                                                                                                        
      - ./plugins-enabled:/home/app/redmine/plugins/   
