---
# redmine.example.com
version: '2'
services:
  mail:
    container_name: "${PREFIX}_mail"
    volumes:
      - "/tmp/exim4:/var/spool/exim4"
    environment:
      ALLOWED_HOSTS: '*'
      PRIMARY_HOST: "${REDMINE_HOST}"

  db:
    container_name: "${PREFIX}_db"

  app:
    container_name: "${PREFIX}_app"
    ports:
      - "${EXTERNAL_PORT}:80"
